// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSPPexTMoLaSUdIxsht9gAkZPGy_8BK-M',
    appId: '1:75072800939:web:3f23fefa2965e447cfcfee',
    messagingSenderId: '75072800939',
    projectId: 'crud22-8c548',
    authDomain: 'crud22-8c548.firebaseapp.com',
    storageBucket: 'crud22-8c548.appspot.com',
    measurementId: 'G-SL6REN4H91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtU8uhdQiJ__9-OgKQJMOhLFn_uAWrNlU',
    appId: '1:75072800939:android:6803f3e0923328fbcfcfee',
    messagingSenderId: '75072800939',
    projectId: 'crud22-8c548',
    storageBucket: 'crud22-8c548.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLE0iCA1rTS06B6yuoHBeEbJuQwZ5HrKw',
    appId: '1:75072800939:ios:9146326d843be38dcfcfee',
    messagingSenderId: '75072800939',
    projectId: 'crud22-8c548',
    storageBucket: 'crud22-8c548.appspot.com',
    iosBundleId: 'com.sysfinal.projectFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLE0iCA1rTS06B6yuoHBeEbJuQwZ5HrKw',
    appId: '1:75072800939:ios:a5c5b5f458e17337cfcfee',
    messagingSenderId: '75072800939',
    projectId: 'crud22-8c548',
    storageBucket: 'crud22-8c548.appspot.com',
    iosBundleId: 'com.sysfinal.projectFinal.RunnerTests',
  );
}
